### ISSUE TITLE
something wrong about dataset.py crop_img()

### ISSUE THREAD

**Issue by YanShuang17** [SakuraRiven/EAST#5]
thanks for your clean code.
but i doubt that if there is something wrong in crop_img() function or not :
after while() loop, if cnt == 1000(flag==True), then there are still some vertices that are outside of the cropped img, these wrong ones should be removed from 'new_vertices' ? 
another question:
suppose that after while() loop, if cnt <1000(flag==False), which means that all vertices are not cross-crop-boundry, but they don't include vertices whose label==0, because you just vertify vertices whose label==1. so if you train with ignored, the valid vertices may be not matched with the cropped img.
waiting for your comment.

**Comment by SakuraRiven** [comment]
@YanShuang17 Hi, thanks for reading these code. 

1. The function `is_cross_text ` is used to judge if the crop has cut the text region, instead of image boundary. If the text is split, the following gt generation (distance and angle) is complicated. I was little lazy at that time to handle such cases...
Indeed, there are some vertices out of crop range. These points don't matter because `cv2.fillPoly` could automatically filter out outliers.

2. After while() loop, if cnt <1000(flag==False), it just means that the crop image doesn't cut any valid text region (`label==1` vertices). And we don't have to care these ignored vertices.
The remain vertices still have `label==0` which would used in function `get_score_geo`.

I hope this answer helps. Umm, this repo may be not the best implementation and just for my practice. OTZ

**Comment by YanShuang17** [comment]
@SakuraRiven Thanks for your explanation!
Sorry, Indeed I didn't read codes about the latter gt generation part, didn't notice cv2.fillPoly(),  I just read the data augmentation part and feel something wrong...now I understand, thank you!
